In [18]:
import numpy as np

In [2]:
# Given data

sample_values = np.array([-5, -3, -1, 1, 3, 5, 3, 1])

bits_per_sample = 3

min_value = -5
max_value = 5

sampling_rate = 8000

In [14]:
# Number of quantization levels

levels = 2 ** bits_per_sample

print("Number of quantization levels:", levels)

Number of quantization levels: 8


In [15]:
# Quantization step

step_size = (max_value - min_value) / levels

print("Quantization step size:", step_size, "V")

Quantization step size: 1.25 V


In [9]:
# Quantize the samples (using mid-rise quantization)

quantized_values = min_value + (
    np.floor((sample_values - min_value) / step_size) + 0.5
) * step_size

print("Original samples:")
print(sample_values)

print("\nQuantized samples:")
print(quantized_values)

Original samples:
[-5 -3 -1  1  3  5  3  1]

Quantized samples:
[-4.375 -3.125 -0.625  0.625  3.125  5.625  3.125  0.625]


In [11]:
# Quantization indices

quantization_indices = np.floor(
    (sample_values - min_value) / step_size
).astype(int)

print("Quantization indices:")
print(quantization_indices)

Quantization indices:
[0 1 3 4 6 8 6 4]


In [13]:
# Convert to Binary

binary_values = [
    format(index, f'0{bits_per_sample}b')          # format(5, '03b') = 101
    for index in quantization_indices
]

print("Binary PCM codes:")

for sample, index, binary in zip(
    sample_values,
    quantization_indices,
    binary_values
):
    print(sample, "->", index, "->", binary)

Binary PCM codes:
-5 -> 0 -> 000
-3 -> 1 -> 001
-1 -> 3 -> 011
1 -> 4 -> 100
3 -> 6 -> 110
5 -> 8 -> 1000
3 -> 6 -> 110
1 -> 4 -> 100


In [16]:
# PCM Bit Rate
bit_rate = sampling_rate * bits_per_sample

print("PCM bit rate:", bit_rate, "bits/s")
print("PCM bit rate:", bit_rate / 1000, "kbps")

PCM bit rate: 24000 bits/s
PCM bit rate: 24.0 kbps
